name: bl_runners_app
description: Para o grupo competir.
publish_to: 'none'

version: 1.0.2+4

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.0
  cloud_firestore: ^4.9.1
  firebase_auth: ^4.7.2
  firebase_storage: ^11.2.5
  firebase_database: ^10.2.5
  go_router: ^10.0.0
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  intl: ^0.18.0
  flutter_localization: ^0.1.14
  image_picker: ^1.0.2
  top_snackbar_flutter: ^3.1.0
  connectivity_plus: ^4.0.2
  logger: ^2.0.2+1
  month_picker_dialog: ^2.0.2
  uuid: ^4.1.0
  numberpicker: ^2.1.2
  collection: ^1.17.2
  cached_network_image: ^3.3.0
  ntp: ^2.0.0
  flutter_markdown: ^0.6.18
  timezone: ^0.9.2
  flutter_datetime_picker_plus: ^2.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/bl_logo.png
    - assets/images/avatar.png
    - assets/images/medalha.png