// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOfMfqrxBLT9qgb-GiriCXL3QuwIOi4OU',
    appId: '1:929303967235:web:e525342f55a0e1eaf00036',
    messagingSenderId: '929303967235',
    projectId: 'blrunners',
    authDomain: 'blrunners.firebaseapp.com',
    storageBucket: 'blrunners.appspot.com',
    measurementId: 'G-7XHHR4JM81',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIH4YDom2ukZDNrxenFhBb0Q9BZ857sa4',
    appId: '1:929303967235:android:2ccdacaad773ce9af00036',
    messagingSenderId: '929303967235',
    projectId: 'blrunners',
    storageBucket: 'blrunners.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGZuZITei1RcoGUjgxKkTB_4agF9-FAp4',
    appId: '1:929303967235:ios:1825b80b07adaf54f00036',
    messagingSenderId: '929303967235',
    projectId: 'blrunners',
    storageBucket: 'blrunners.appspot.com',
    iosClientId: '929303967235-th8p7oti705pu1lr0goe997b0llpq3ff.apps.googleusercontent.com',
    iosBundleId: 'com.example.blRunnersFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGZuZITei1RcoGUjgxKkTB_4agF9-FAp4',
    appId: '1:929303967235:ios:3606da2670e9fb3ef00036',
    messagingSenderId: '929303967235',
    projectId: 'blrunners',
    storageBucket: 'blrunners.appspot.com',
    iosClientId: '929303967235-2n7vcs77vb7ce9v63g9dmuiig542bdej.apps.googleusercontent.com',
    iosBundleId: 'com.example.blRunnersFirebase.RunnerTests',
  );
}
