// File generated by FlutterFire CLI..
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXxdHWTs5erlLKo_qdJnwUI7blJcOmPXk',
    appId: '1:476972778862:web:f4f855e09d3915069fad7f',
    messagingSenderId: '476972778862',
    projectId: 'blrunners-app',
    authDomain: 'blrunners-app.firebaseapp.com',
    storageBucket: 'blrunners-app.appspot.com',
    measurementId: 'G-HDJ1M4CHPS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2R8Kp13JTbF_2cWzZTK8fMk-hE0noxRQ',
    appId: '1:476972778862:android:0b6fc4ebda7b72649fad7f',
    messagingSenderId: '476972778862',
    projectId: 'blrunners-app',
    storageBucket: 'blrunners-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfSKE29WJhDapJTTB_Wq6Sca8eGd6t4WA',
    appId: '1:476972778862:ios:8b29516fc98d05219fad7f',
    messagingSenderId: '476972778862',
    projectId: 'blrunners-app',
    storageBucket: 'blrunners-app.appspot.com',
    iosClientId:
        '476972778862-1s9ugdqfin0bi698q99ehg39iit2qd7f.apps.googleusercontent.com',
    iosBundleId: 'com.example.blRunnersFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfSKE29WJhDapJTTB_Wq6Sca8eGd6t4WA',
    appId: '1:476972778862:ios:beac62cb1f56457f9fad7f',
    messagingSenderId: '476972778862',
    projectId: 'blrunners-app',
    storageBucket: 'blrunners-app.appspot.com',
    iosClientId:
        '476972778862-4arjnpsmdiu8qbo6fkll444e072bkr9p.apps.googleusercontent.com',
    iosBundleId: 'com.example.blRunnersFirebase.RunnerTests',
  );
}
